# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/FPGA/DigitalRX/DigitalRX.srcs/sources_1/ip/xfft/xfft.xci
# IP: The module: 'xfft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DigitalRX/DigitalRX.gen/sources_1/ip/xfft/xfft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/FPGA/DigitalRX/DigitalRX.srcs/sources_1/ip/xfft/xfft.xci
# IP: The module: 'xfft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/DigitalRX/DigitalRX.gen/sources_1/ip/xfft/xfft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xfft'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
